repositories {
    mavenLocal()
    mavenCentral()
    // force gradle to download FastUtil & LWJGL from the central maven so we can get source artifacts
    exclusiveContent { // Force
        forRepository { mavenCentral() }
        filter {
            includeGroup("it.unimi.dsi")
            includeGroup("org.lwjgl")
            includeGroup("com.google.guava")
            includeGroup("io.netty")
        }
    }
    maven { // JEI
        name = "Jared's Maven"
        url = "https://maven.blamejared.com/"
    }
    maven { // JEI mirror, AE2
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven { // LDLib, Shimmer
        name = "FirstDarkDev Maven"
        url = "https://maven.firstdark.dev/snapshots"
    }
    exclusiveContent { // shedaniel - REI, architectury, cloth-config
        forRepository { maven { url = "https://maven.shedaniel.me/" } }
        filter {
            includeGroupAndSubgroups("me.shedaniel")
            includeGroup("dev.architectury")
        }
    }
    exclusiveContent { // KotlinForForge
        forRepository { maven { url = "https://thedarkcolour.github.io/KotlinForForge/" } }
        filter { includeGroup("thedarkcolour") }
    }
    exclusiveContent { // tterrag - registrate
        forRepository { maven { url = "https://maven.gegy.dev/releases" } }
        filter { includeGroup("com.tterrag.registrate") }
    }
    exclusiveContent { // Configuration
        forRepository { maven { url = "https://repo.repsy.io/mvn/toma/public" } }
        filter { includeGroup("dev.toma.configuration")}
    }
    exclusiveContent { // terraformers - EMI
        forRepository { maven { url = "https://maven.terraformersmc.com/releases/" } }
        filter { includeGroup("dev.emi") }
    }
    exclusiveContent { // Modrinth Maven
        forRepository { maven { url = "https://api.modrinth.com/maven" } }
        filter { includeGroup("maven.modrinth") }
    }
    exclusiveContent { // Curseforge Maven
        forRepository { maven { url = "https://cursemaven.com" } }
        filter { includeGroup("curse.maven") }
    }
}
