dependencies {
    compileOnly(libs.jetbrains.annotations)

    testImplementation(libs.testframework.get())

    jarJar(forge.kotlinforforge.get())

    jarJar(api(forge.ldlib2.get()))

    // Registrate
    jarJar(api(forge.registrate.get()))

    // Configuration
    jarJar(api(forge.configuration.get()))

    compileOnly(forge.kotlinforforge)

    // Recipe Viewers
    compileOnly(forge.bundles.jei)
    compileOnly(forge.emi)

    // WAILA-likes
    compileOnly(forge.jade)

    // Curios
    compileOnly(variantOf(forge.curios) { classifier("api") })

    // AE2
    compileOnly(forge.ae2)

    // Create
    compileOnly(forge.ponder)
    compileOnly(variantOf(forge.create) { classifier("slim") })
    compileOnly(forge.flywheel.forge.api)

    // KJS
    compileOnly(forge.bundles.kjs)

    // Rendering / Optimizations
    compileOnly(forge.sodium)
    compileOnly(forge.iris)
    compileOnly(forge.modernfix)

    // Teams
    compileOnly(forge.ftblibrary)
    compileOnly(forge.ftbteams)
    compileOnly(forge.ftbquests)
    compileOnly(forge.resourcefullib)
    compileOnly(forge.argonauts)
    compileOnly(forge.heracles)

    // Maps
    compileOnly(forge.ftbchunks)
    compileOnly(forge.xaeroslib)
    compileOnly(forge.xaerosminimap)
    compileOnly(forge.xaerosworldmap)
    compileOnly(forge.journeymap.api)
    compileOnly(forge.journeymap.forge)

    // CC: Tweaked
    compileOnly(forge.cc.tweaked.core.api)
    compileOnly(forge.cc.tweaked.forge.api)


    // Standard runtime mods //
    localRuntime(forge.kotlinforforge)

    localRuntime(forge.jade)
    localRuntime(forge.spark)

    // Runtime Recipe Viewers - uncomment whichever one you want to use //
    localRuntime(forge.emi)
    localRuntime(forge.jei.neoforge.impl)

    // Client-only runtime mods //
    clientLocalRuntime(forge.sodium)
    clientLocalRuntime(forge.iris)
    renderNurseCfg(libs.renderNurse)

    //////////////////////////////////////////////////////
    // Runtime mods for dev testing with unclean client //
    //////////////////////////////////////////////////////

    //////////////////////////

}
