org.gradle.jvmargs = -Xmx6G
org.gradle.java.installations.auto-download=false
org.gradle.parallel = true
org.gradle.caching = true

# Mod Info
mod_id = extfrocore
mod_name = ExtremelyFrozenCore
mod_version = 0.0.3
mod_description =
mod_license = GNU AGPL 3.0
mod_url = https://github.com/ExtremelyFrozen/ExtremelyFrozenCore
mod_issue_tracker = https://github.com/ExtremelyFrozen/ExtremelyFrozenCore/issues/
maven_group = com.extfro.extfrocore
