[versions]
kotlinforforge = "5.11.0"
ldlib = "2.2.8"
registrate = "MC1.21.1-1.4.6"
configuration = "3.1.1-neoforge"

jei = "19.27.0.340"
rei = "16.0.799"
emi = "1.1.22+1.21.1"


## modrinth maven ##

## curseforge maven ##

## libs ##


[libraries]
kotlinforforge      = { module = "thedarkcolour:kotlinforforge-neoforge", version.ref = "kotlinforforge" }
ldlib               = { module = "com.lowdragmc.ldlib2:ldlib2-neoforge-1.21.1", version.ref = "ldlib" }
registrate          = { module = "com.tterrag.registrate:Registrate", version.ref = "registrate" }
configuration       = { module = "dev.toma.configuration:configuration-1.21.1", version.ref = "configuration" }

jei-common-api      = { module = "mezz.jei:jei-1.21.1-common-api", version.ref = "jei" }
jei-neoforge-api    = { module = "mezz.jei:jei-1.21.1-neoforge-api", version.ref = "jei" }
jei-neoforge-impl   = { module = "mezz.jei:jei-1.21.1-neoforge", version.ref = "jei" }
rei-plugin          = { module = "me.shedaniel:RoughlyEnoughItems-default-plugin-neoforge", version.ref = "rei" }
rei-api             = { module = "me.shedaniel:RoughlyEnoughItems-api-neoforge", version.ref = "rei" }
rei-neoforge        = { module = "me.shedaniel:RoughlyEnoughItems-neoforge", version.ref = "rei" }
emi                 = { module = "dev.emi:emi-neoforge", version.ref = "emi" }


[bundles]
jei = ["jei-common-api", "jei-neoforge-api", "jei-neoforge-impl"]
rei = ["rei-plugin", "rei-neoforge"]
#rei-runtime = ["rei-neoforge", "architectury", "clothconfig"]
#kjs = ["kubejs", "rhino"]